languageCode = "en-us"
title = "On Software Engineering"
theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "custom-theme.scss"
custom_theme_compile = true
width = 1280
height = 720
margin = 0.01

